### ISSUE TITLE
order of data frame rows

### ISSUE THREAD

**Issue by ggrothendieck** [patrickroocks/listcompr#2]
I would have thought that these two would result in different order of rows but they are the same.  Is this intended?

```
> gen.data.frame(data.frame(a = i, b = j), j = 0:2, i = 1:2)
  a b
1 1 0
2 2 0
3 1 1
4 2 1
5 1 2
6 2 2
> gen.data.frame(data.frame(a = i, b = j), i = 1:2, j = 0:2)
  a b
1 1 0
2 2 0
3 1 1
4 2 1
5 1 2
6 2 2
```

**Comment by patrickroocks** [comment]
Thanks a lot for that finding! No that was not intended.

It is intended that all indexed vars are kept together and sorted, even if some of them are overwritten, e.g.

     gen.vector(x_1 + x_2 + a, x_ = 1:5, a = 1:2, x_1 = 1:2)

should be interpreted as

     gen.vector(x_1 + x_2 + a, x_1 = 1:2, x_2 = 1:5, a = 1:2)

Stupidly I solved that by simply sorting all variables alphabetically before putting it to the R internal function `expand.grid`. 

Just fixed with my last commit.

I hope, it is intuitive that indexed vars are sorted? (Idea: Overwriting x_1 should not change the "position" of x_1)
